name: teminator
channels:
    - conda-forge
dependencies:
    - python=3.14.*
    - numpy>=2.0
    - scipy
    - pyqtgraph
    - pyqt=5.15.*
    - hyperspy
    - exspy
    - sparse #enable loading of spectrum images
